frequency: 30.0
sensor_timeout: 0.1 # seconds
two_d_mode: true # we operate a ground robot so 2D
publish_tf: true
print_diagnostics: true
debug: true

base_link_frame: base_footprint
odom_frame: odom
world_frame: map
map_frame : map

# Postion:         x,     y,     z
# Orientation:  roll, pitch,   yaw
# Linear Velocity: x,     y,     z
# Velocity:     roll, pitch,   yaw
# Accel:           x,     y,     z

# odom configuration
odom0: /tu_delft_base_control/odom
odom0_config: [false, false, false,   
               false, false, false,   
               true, true, false,     
               false, false, true,    
               false, false, false]
odom0_differential: false
odom0_relative: false
odom0_queue_size: 10

# odom configurationfrom gps
odom1: /odometry/gps
odom1_config: [true, true, false,     
               false, false, false,
               false, false, false,
               false, false, false,
               false, false, false]
odom1_differential: false
odom1_relative: false
odom1_queue_size: 10

# imu configuration
imu0: /imu
imu0_config: [true, true, false,
              false, false, false,
              false, false, false, 
              false, false, true,  
              false, false, false]
imu0_differential: false
imu0_relative: false
imu0_remove_gravitational_acceleration: true
imu0_queue_size: 10

# imu0_orientation_covariance: [0.0, 0.0, 0.0,
#                               0.0, 0.0, 0.0,
#                               0.0, 0.0, 0.1]  # yaw variance: 0.01 rad^2 (no need for roll/pitch cause 2D)

# imu0_angular_velocity_covariance: [0.0, 0.0, 0.0,
#                                    0.0, 0.0, 0.0,
#                                    0.0, 0.0, 0.1]  # yaw rate variance: 0.001 rad^2/s^2

# imu0_linear_acceleration_covariance: [0.0, 0.0, 0.0,
#                                       0.0, 0.0, 0.0,
#                                       0.0, 0.0, 0.0]  # not used

process_noise_covariance: [0.05,    0,    0,    0,    0,    0,     0,     0,    0,     0,    0,    0,    0,    0,     0,
                              0, 0.05,    0,    0,    0,    0,     0,     0,    0,     0,    0,    0,    0,    0,     0,
                              0,    0, 0.06,    0,    0,    0,     0,     0,    0,     0,    0,    0,    0,    0,     0,
                              0,    0,    0, 0.03,    0,    0,     0,     0,    0,     0,    0,    0,    0,    0,     0,
                              0,    0,    0,    0, 0.03,    0,     0,     0,    0,     0,    0,    0,    0,    0,     0,
                              0,    0,    0,    0,    0, 0.06,     0,     0,    0,     0,    0,    0,    0,    0,     0,
                              0,    0,    0,    0,    0,    0, 0.025,     0,    0,     0,    0,    0,    0,    0,     0,
                              0,    0,    0,    0,    0,    0,     0, 0.025,    0,     0,    0,    0,    0,    0,     0,
                              0,    0,    0,    0,    0,    0,     0,     0, 0.04,     0,    0,    0,    0,    0,     0,
                              0,    0,    0,    0,    0,    0,     0,     0,    0,  0.01,    0,    0,    0,    0,     0,
                              0,    0,    0,    0,    0,    0,     0,     0,    0,     0, 0.01,    0,    0,    0,     0,
                              0,    0,    0,    0,    0,    0,     0,     0,    0,     0,    0, 0.02,    0,    0,     0,
                              0,    0,    0,    0,    0,    0,     0,     0,    0,     0,    0,    0, 0.01,    0,     0,
                              0,    0,    0,    0,    0,    0,     0,     0,    0,     0,    0,    0,    0, 0.01,     0,
                              0,    0,    0,    0,    0,    0,     0,     0,    0,     0,    0,    0,    0,    0, 0.005]

initial_estimate_covariance:  [1e-9,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
                                  0, 1e-9,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
                                  0,    0, 1e-9,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
                                  0,    0,    0, 1e-9,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
                                  0,    0,    0,    0, 1e-9,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
                                  0,    0,    0,    0,    0, 1e-9,    0,    0,    0,    0,    0,    0,    0,    0,    0,
                                  0,    0,    0,    0,    0,    0, 1e-9,    0,    0,    0,    0,    0,    0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0, 1e-9,    0,    0,    0,    0,    0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0, 1e-9,    0,    0,    0,    0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0, 1e-9,    0,    0,    0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 1e-9,    0,    0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 1e-9,    0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 1e-9,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 1e-9,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 1e-9]

